[package]
name = "i18n"
version = "0.1.0"
edition = "2021"
authors = ["Mark Liwag <markhenry.liwag@gmail.com>"]

[dependencies]
fluent-templates = "0.11.0"
lazy_static = "1.4.0"
once_cell = "1.18.0"
unic-langid = "0.9.4"